version: '3'
services:
  eureka-server:
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8888:8888"
    networks:
      - eureka-network

  mc-account:
    container_name: mc-account
    image: mc-account-image
    build: .
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8888/eureka/
      - EUREKA_CLIENT_REGISTERWITH_EUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=false
    depends_on:
      - eureka-server
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge