spring:
  application:
    name: mc-account
  jpa:
    generate-ddl: false
    open-in-view: true
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: 1234
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQL9Dialect

app:
  kafka:
    kafkaMessageTopic: "updateTopic"
    kafkaMessageGroupId: "account_consumer"
    bootstrap-servers: localhost:9092

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml