spring:
  application:
    name: mc-account
  jpa:
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5435/database
    username: postgres
    password: postgres
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092


app:
  kafka:
    kafkaMessageTopic: "updateTopic"
    kafkaMessageGroupId: "account_consumer"
server:
  port: 8089
